# Generated by Django 4.1.3 on 2022-11-14 07:19

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('mobile_number', models.CharField(help_text='-> Phone number should be of 10 digits <br/> \n-> Phone number must starts with either 9, 8, 7 or 6 <br/>\n-> Should enter in this format: 9999955555', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[6-9]\\d{9}$')])),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expired_at', models.IntegerField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.IntegerField(default=1668410384.53717, editable=False)),
                ('update_at', models.IntegerField(default=1668410384.537181, editable=False)),
                ('delete_at', models.IntegerField(default=1668410384.537187)),
            ],
        ),
    ]
