# Generated by Django 4.1.3 on 2022-11-15 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OtpView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.IntegerField(default=1668487379.980292, editable=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='delete_at',
            field=models.IntegerField(default=1668487379.9803069),
        ),
        migrations.AlterField(
            model_name='otp',
            name='update_at',
            field=models.IntegerField(default=1668487379.9803011, editable=False),
        ),
        migrations.CreateModel(
            name='SendMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.IntegerField(default=1668487379.980685, editable=False)),
                ('update_at', models.IntegerField(default=1668487379.980693, editable=False)),
                ('otp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtpView.otp')),
            ],
        ),
    ]
