# Generated by Django 4.1.3 on 2022-11-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtpView', '0002_alter_otp_created_at_alter_otp_delete_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='otp_expired_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='otp_verified',
        ),
        migrations.AddField(
            model_name='sendmessages',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='sendmessages',
            name='otp_expired_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sendmessages',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.IntegerField(default=1668491032.674898, editable=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='delete_at',
            field=models.IntegerField(default=1668491032.674912),
        ),
        migrations.AlterField(
            model_name='otp',
            name='update_at',
            field=models.IntegerField(default=1668491032.674907, editable=False),
        ),
        migrations.AlterField(
            model_name='sendmessages',
            name='created_at',
            field=models.IntegerField(default=1668491032.675317, editable=False),
        ),
        migrations.AlterField(
            model_name='sendmessages',
            name='update_at',
            field=models.IntegerField(default=1668491032.6753228, editable=False),
        ),
    ]
